# Generated by Django 3.2.9 on 2021-12-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsByPhone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbyphonenumber',
            name='is_superuser',
        ),
        migrations.AlterField(
            model_name='userbyphonenumber',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Yosh'),
        ),
    ]
