# Generated by Django 3.2.9 on 2021-12-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsByPhone', '0002_auto_20211221_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbyphonenumber',
            name='age',
            field=models.IntegerField(),
        ),
    ]
