# Generated by Django 3.2.9 on 2021-12-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsByPhone', '0003_alter_userbyphonenumber_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbyphonenumber',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Yosh'),
        ),
    ]
