# Generated by Django 3.2.9 on 2021-12-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsByPhone', '0004_alter_userbyphonenumber_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbyphonenumber',
            name='phone_number',
            field=models.IntegerField(null=True, unique=True, verbose_name='Telefon Raqam'),
        ),
    ]
